language: android
dist: trusty
os: linux
jdk: openjdk11
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
    - android-31
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-addon-google_apis-google-31
    - sys-img-armeabi-v7a-addon-google_apis-google-24

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - TARGET_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_HOME=~/android-sdk

before_install:
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
script:
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  #- export CODECOV_TOKEN="85d3b8be-ce43-4374-8230-15da233d5615"
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false