version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies, run tests, and collect coverage
          command: ./gradlew build
      - codecov/upload
      - file: coverage.xml,e2e-coverage.xml

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
