name: Android CI
on:
  push:
    branches: [ karabo_new ]
  pull_request:
    branches: [ karabo_new ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '18'
          distribution: 'adopt'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest
        
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2 
        with:
          api-level: 21
          script: ./gradlew connectedCheck
          
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
