name: Workflow for Codecov example-java-maven
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Upload tests results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: |
            ./coverage.xml
  uplaod_coverage_results:
    needs: run 
    runs-on: ubuntu-latest
    name: "Upload code coverage"
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Download tests results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          
      - name: Check files
        run: |
          cat ./coverage.xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
