name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      #- name: Install dependencies, run tests, and collect coverage
      #  run: gradle build
      # Execute unit tests
      - name: Gradlew Permission
        run: chmod +x ./gradlew
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
